"""CNIG Accessibility standard v2021-10 rev.2026-04

Auto-generated by `alembic revision --autogenerate` then completed:
  - Data migration: quai/stationnement_pmr.etatRevetement remapped
    (constraint etat -> etat_revetement; e.g. "bon état" -> "roulant")
  - Added columns: escalier.regularite, escalier.rampeInterne,
    ascenseur.opaciteParois
  - Rename (batch): stationnement_pmr.idStationnement -> idStationnementPmr
  - Trigger updated: trg_stationnement_pmr_set_id
  - OGC gpkg_schema extension: updated enumeration constraints
    (etat +2 values, type_troncon +1 value, new lists regularite /
    rampe_interne) and column->constraint mappings (quai, stationnement_pmr,
    escalier)

Revision ID: 002
Revises: 001
Create Date: 2026-04-23
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "002"
down_revision: Union[str, Sequence[str], None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from cnig_accessibilite.cnig_versions.v2026.enums import ETAT, TYPE_TRONCON, REGULARITE, RAMPE_INTERNE
    from cnig_accessibilite.cnig_versions.mappings import (
        ETAT_V001_TO_ETAT_REVETEMENT_V002,
        ETAT_V001_TO_ETAT_V002,
        TYPE_TRONCON_V001_TO_TYPE_TRONCON_V002,
    )
    from cnig_accessibilite.cnig_versions.v2025.enums import COLUMN_SPECS as OLD_SPECS
    from cnig_accessibilite.cnig_versions.v2026.enums import COLUMN_SPECS as NEW_SPECS
    from cnig_accessibilite.migration_helpers import (
        create_id_trigger, drop_id_trigger,
        upsert_enum_constraint, insert_enum_constraint,
        update_column_constraint, add_column_constraint,
        remap_constraint_values,
    )

    # 0. Data migration: remap changed values
    # etat columns switching to etat_revetement constraint (quai, stationnement_pmr)
    remap_constraint_values("etat", ETAT_V001_TO_ETAT_REVETEMENT_V002,
                            old_specs=OLD_SPECS, new_specs=NEW_SPECS,
                            new_constraint="etat_revetement")
    # etat columns keeping etat constraint
    remap_constraint_values("etat", ETAT_V001_TO_ETAT_V002,
                            old_specs=OLD_SPECS, new_specs=NEW_SPECS)
    remap_constraint_values("type_troncon", TYPE_TRONCON_V001_TO_TYPE_TRONCON_V002,
                            old_specs=OLD_SPECS, new_specs=NEW_SPECS)

    # 1. New columns
    with op.batch_alter_table("ascenseur", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("opaciteParois", sa.Integer(), nullable=True))

    with op.batch_alter_table("escalier", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("regularite",   sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("rampeInterne", sa.Text(), nullable=True))

    # 2. Rename column
    # idStationnement -> idStationnementPmr
    drop_id_trigger("stationnement_pmr")
    with op.batch_alter_table("stationnement_pmr", schema=None) as batch_op:
        batch_op.alter_column(
            "idStationnement", new_column_name="idStationnementPmr")
    create_id_trigger("stationnement_pmr", "idStationnementPmr", "STA")

    # 3. Add / Update value lists: gpkg_data_column_constraints
    upsert_enum_constraint("etat",         ETAT)
    upsert_enum_constraint("type_troncon", TYPE_TRONCON)
    insert_enum_constraint("regularite",   REGULARITE)
    insert_enum_constraint("rampe_interne", RAMPE_INTERNE)

    # 4. Add / Update column constraint mappings: gpkg_data_columns
    for table in ("quai", "stationnement_pmr"):
        update_column_constraint(table, "etatRevetement", "etat_revetement")
    add_column_constraint("escalier", "regularite",
                          "regularite",   "caractère régulier de l'escalier")
    add_column_constraint("escalier", "rampeInterne", "rampe_interne",
                          "présence d'une rampe de conduite d'objets, interne à l'escalier")


def downgrade() -> None:
    from cnig_accessibilite.cnig_versions.v2025.enums import ETAT, TYPE_TRONCON
    from cnig_accessibilite.cnig_versions.mappings import (
        ETAT_REVETEMENT_V002_TO_ETAT_V001,
        ETAT_V002_TO_ETAT_V001,
        TYPE_TRONCON_V002_TO_TYPE_TRONCON_V001,
    )
    from cnig_accessibilite.cnig_versions.v2025.enums import COLUMN_SPECS as V2025_SPECS
    from cnig_accessibilite.cnig_versions.v2026.enums import COLUMN_SPECS as V2026_SPECS
    from cnig_accessibilite.migration_helpers import (
        create_id_trigger, drop_id_trigger,
        upsert_enum_constraint, delete_enum_constraint,
        update_column_constraint, remove_column_constraint,
        remap_constraint_values,
    )

    # 4. Restore column constraint mappings: gpkg_data_columns
    remove_column_constraint("escalier", "regularite")
    remove_column_constraint("escalier", "rampeInterne")
    for table in ("quai", "stationnement_pmr"):
        update_column_constraint(table, "etatRevetement", "etat")

    # 3. Restore value lists: gpkg_data_column_constraints
    delete_enum_constraint("regularite")
    delete_enum_constraint("rampe_interne")
    upsert_enum_constraint("etat",         ETAT)
    upsert_enum_constraint("type_troncon", TYPE_TRONCON)

    # 2. Rename column
    # idStationnementPmr -> idStationnement
    drop_id_trigger("stationnement_pmr")
    with op.batch_alter_table("stationnement_pmr", schema=None) as batch_op:
        batch_op.alter_column("idStationnementPmr",
                              new_column_name="idStationnement")
    create_id_trigger("stationnement_pmr", "idStationnement", "STA")

    # 1. Drop added columns
    with op.batch_alter_table("escalier", schema=None) as batch_op:
        batch_op.drop_column("rampeInterne")
        batch_op.drop_column("regularite")

    with op.batch_alter_table("ascenseur", schema=None) as batch_op:
        batch_op.drop_column("opaciteParois")

    # 0. Reverse data migration
    # etat_revetement columns reverting to etat constraint (quai, stationnement_pmr)
    remap_constraint_values("etat_revetement", ETAT_REVETEMENT_V002_TO_ETAT_V001,
                            old_specs=V2026_SPECS, new_specs=V2025_SPECS,
                            new_constraint="etat")
    # etat columns keeping etat constraint
    remap_constraint_values("etat", ETAT_V002_TO_ETAT_V001,
                            old_specs=V2026_SPECS, new_specs=V2025_SPECS)
    remap_constraint_values("type_troncon", TYPE_TRONCON_V002_TO_TYPE_TRONCON_V001,
                            old_specs=V2026_SPECS, new_specs=V2025_SPECS)
