"""CNIG Accessibility standard value lists — current version.

Always re-exports the latest standard revision.
For a specific snapshot:
    from cnig_accessibilite.versions.v2025.enums import ...
    from cnig_accessibilite.versions.v2026.enums import ...
"""
from .cnig_versions.v2026.enums import (
    NC, SANS_OBJET,
    CATEGORIE_ERP, CONTROLE_ACCES, CONTROLE_BEV, COTE, COUVERT,
    DISPOSITIF_SIGNALISATION, ECLAIRAGE, ETAT, ETAT_REVETEMENT,
    MARQUAGE, MASQUE_COVISIBILITE, PERSONNEL_ERP,
    POSITION_ESPACE, POSITION_HAUTEUR, POSITION_OBSTACLE,
    RAMPE_ERP, RAMPE_INTERNE, RAPPEL_OBSTACLE, REGULARITE, RELIEF_BOUTONS,
    REPERE_LINEAIRE, SENS, STATUT_VOIE, TEMPORALITE, TRANSITION,
    TYPE_ENTREE, TYPE_ERP, TYPE_OBSTACLE, TYPE_OUVERTURE, TYPE_PASSAGE,
    TYPE_POIGNEE, TYPE_PORTE, TYPE_SOL, TYPE_STATIONNEMENT, TYPE_TRONCON,
    VOYANT_ASCENSEUR,
    ENUM_CONSTRAINTS, COLUMN_SPECS, COLUMN_CONSTRAINTS, COLUMN_DESCRIPTIONS, MULTIVALUE_COLUMNS,
    allowed_values, validate,
)

__all__ = [
    "NC", "SANS_OBJET",
    "CATEGORIE_ERP", "CONTROLE_ACCES", "CONTROLE_BEV", "COTE", "COUVERT",
    "DISPOSITIF_SIGNALISATION", "ECLAIRAGE", "ETAT", "ETAT_REVETEMENT",
    "MARQUAGE", "MASQUE_COVISIBILITE", "PERSONNEL_ERP",
    "POSITION_ESPACE", "POSITION_HAUTEUR", "POSITION_OBSTACLE",
    "RAMPE_ERP", "RAMPE_INTERNE", "RAPPEL_OBSTACLE", "REGULARITE", "RELIEF_BOUTONS",
    "REPERE_LINEAIRE", "SENS", "STATUT_VOIE", "TEMPORALITE", "TRANSITION",
    "TYPE_ENTREE", "TYPE_ERP", "TYPE_OBSTACLE", "TYPE_OUVERTURE", "TYPE_PASSAGE",
    "TYPE_POIGNEE", "TYPE_PORTE", "TYPE_SOL", "TYPE_STATIONNEMENT", "TYPE_TRONCON",
    "VOYANT_ASCENSEUR",
    "ENUM_CONSTRAINTS", "COLUMN_SPECS", "COLUMN_CONSTRAINTS", "COLUMN_DESCRIPTIONS", "MULTIVALUE_COLUMNS",
    "allowed_values", "validate",
]
